# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-10 20:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='text',
        ),
    ]
