# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-10 20:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_message_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='read_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
