# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-30 19:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_log', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shareitem',
            name='purchasers',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='shareitem',
            name='receipt_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchase_log.ReceiptProduct'),
        ),
    ]
