# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-09 00:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_log', '0002_auto_20161007_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='tax',
            field=models.FloatField(default=0.07),
            preserve_default=False,
        ),
    ]
