# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-09 18:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_log', '0003_receipt_tax'),
    ]

    operations = [
        migrations.AddField(
            model_name='receiptproduct',
            name='tax',
            field=models.BooleanField(default=True),
        ),
    ]
