# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-19 18:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_log', '0004_receiptproduct_tax'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='split',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='receiptproduct',
            name='co_owner',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='receiptproduct',
            name='split',
            field=models.BooleanField(default=True),
        ),
    ]
