# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-20 18:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_log', '0005_auto_20161019_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='split',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
