# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-20 18:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_log', '0006_auto_20161020_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='co_owner',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='split',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='receiptproduct',
            name='co_owner',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
