# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-24 17:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_log', '0007_auto_20161020_1449'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipt',
            name='co_owner',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='split',
        ),
        migrations.RemoveField(
            model_name='receiptproduct',
            name='co_owner',
        ),
        migrations.RemoveField(
            model_name='receiptproduct',
            name='split',
        ),
    ]
