# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-24 18:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('purchase_log', '0008_auto_20161024_1355'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShareItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchasers', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('receipt_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchase_log.ReceiptProduct')),
            ],
        ),
    ]
