# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-24 18:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_log', '0009_shareitems'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ShareItems',
            new_name='ShareItem',
        ),
        migrations.AddField(
            model_name='receipt',
            name='split',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='receiptproduct',
            name='split',
            field=models.BooleanField(default=False),
        ),
    ]
