# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-24 19:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('purchase_log', '0010_auto_20161024_1450'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shareitem',
            name='purchasers',
        ),
        migrations.AddField(
            model_name='shareitem',
            name='purchasers',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
