# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-25 18:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_log', '0012_auto_20161025_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shareitem',
            name='receipt_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='purchase_log.ReceiptProduct'),
        ),
    ]
