# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-08 19:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_log', '0013_auto_20161025_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
